### ISSUE TITLE
Marechai site disconnecting

### ISSUE THREAD

**Issue by tapitanlg** [claunia/marechai#23]
Marechai is currently disconnecting several times and taking some time to reconect, it seems to disconect every half an hour specially the last few days (23/07/2020)
![Screenshot_6](https://user-images.githubusercontent.com/66862286/88354324-e610a500-cd36-11ea-893f-d9162a330f8e.png)
![Screenshot_7](https://user-images.githubusercontent.com/66862286/88354402-27a15000-cd37-11ea-9dc8-d0a21541dfdf.png)

**Comment by claunia** [comment]
Hi,

This is a scheduled maintenance script gone rogue by the internet provider.

I have already contacted support and are awaiting their fix.

It happens a few times everyday between 1am and 4am UTC.
